spring:

  datasource:
    url: jdbc:postgresql://localhost:8080/ilanikolaev
    username: ilanikolaev
    password: ilanikolaev
  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: 'true'
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
  application:
    name: task-manager
server:
  port: 8081

